language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t ericamendez/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ericamendez/docker-react npm run test